// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pos.Product.Infrastructure;

namespace Pos.Product.Infrastructure.Migrations
{
    [DbContext(typeof(POSProductContext))]
    [Migration("20210115073408_InitProduct")]
    partial class InitProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pos.Product.Domain.ProductAggregate.MstProduct", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("Category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("Quantity");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Pos.Product.Domain.ProductAggregate.ProductCategory", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("Pos.Product.Domain.ProductAggregate.MstProduct", b =>
                {
                    b.HasOne("Pos.Product.Domain.ProductAggregate.ProductCategory", "CategoryNavigation")
                        .WithMany("Product")
                        .HasForeignKey("Category")
                        .HasConstraintName("FK_Product_ProductCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
